export { defineConfig, definePlugin, defineRule } from './define'
export type {
  AlintConfig,
  AlintConfigExtends,
  AlintConfigInput,
  AlintConfigItem,
  AlintLinterOptions,
  Awaitable,
  DiagnosticDescriptor,
  DiagnosticLocation,
  DirectoryTarget,
  EnabledRule,
  IgnoreConfig,
  LanguageDefinition,
  PluginDefinition,
  ProcessorDefinition,
  ProjectTarget,
  RuleCacheConfig,
  RuleConfigEntry,
  RuleContext,
  RuleDefinition,
  RuleHandlers,
  RuleInferenceUsageRecord,
  RuleOptionsInput,
  RuleOptionsOutput,
  RuleOptionsSchema,
  RuleRegistry,
  RuleSeverity,
  RuleSpecializedHandlers,
  RuleWithHandler,
  Target,
} from './types'
