export type {
  AlintConfig,
  AlintConfigExtends,
  AlintConfigInput,
  AlintConfigItem,
  AlintLinterOptions,
  Awaitable,
  CallSite,
  ClassTarget,
  DiagnosticDescriptor,
  DiagnosticLocation,
  DirectoryTarget,
  EnabledRule,
  FileTarget,
  FunctionInfo,
  FunctionTarget,
  IgnoreConfig,
  LanguageContext,
  LanguageDefinition,
  LineRange,
  ModelRequirement,
  PluginDefinition,
  ProcessedSource,
  ProcessedSourceOrigin,
  ProcessorContext,
  ProcessorDefinition,
  ProcessorPostprocessContext,
  ProjectTarget,
  ResolvedModel,
  ResolvedProvider,
  RuleCacheConfig,
  RuleConfigEntry,
  RuleContext,
  RuleDefinition,
  RuleHandlers,
  RuleInferenceUsageRecord,
  RuleRegistry,
  RuleSeverity,
  RuleSpecializedHandlers,
  RuleWithHandler,
  SourceFile,
  SourceLocation,
  SourcePosition,
  SourceRange,
  SourceRuntime,
  SourceTarget,
  SourceTargetKind,
  SourceTargetOfKind,
  SourceTargetOrigin,
  SourceText,
  Target,
} from '@alint-js/core'

export type {
  AgentAdapter,
  AgentRequest,
  AgentResult,
  AgentTool,
  AgentUsage,
} from '@alint-js/core/agent'

export {
  defineTool,
  isRetryableAgentError,
  requireAgent,
  RetryableAgentError,
} from '@alint-js/core/agent'
export { defineConfig, definePlugin, defineRule } from '@alint-js/core/dsl'
// Via the subpath, never the root: the root would pull core's whole runtime into this dist. See the
// note on `@alint-js/core/languages`.
export { requireLanguage } from '@alint-js/core/languages'
